name: Deploy to Minio Storage

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Static Website to Minio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variable for branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Install Minio Client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/mc

      - name: Configure Minio Client
        run: |
          mc alias set gcp_minio ${{ secrets.MINIO_ENDPOINT }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
          
      - name: Debug Minio connection
        run: |
          mc ls gcp_minio/fire-recovery-web/
          echo "Current content in target bucket"

      - name: Deploy to production bucket
        if: env.BRANCH_NAME == 'main'
        run: |
          echo "Deploying to production bucket"
          mc mirror --overwrite --debug --summary src/ gcp_minio/fire-recovery-web/prod/
          echo "Verifying deployment..."
          mc ls gcp_minio/fire-recovery-web/prod/

      - name: Deploy to development bucket
        if: env.BRANCH_NAME == 'dev'
        run: |
          echo "Deploying to development bucket"
          mc mirror --overwrite --debug --summary src/ gcp_minio/fire-recovery-web/dev/
          echo "Verifying deployment..."
          mc ls gcp_minio/fire-recovery-web/dev/