name: Deploy to Minio Storage

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Static Website to Minio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variable for branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Deploy to production bucket
        if: env.BRANCH_NAME == 'main'
        uses: mamal72/minio-perfect-deploy-action@main
        continue-on-error: true
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'fire-recovery-web'
          source_dir: 'src'
          target_dir: '/prod'

      - name: Deploy to development bucket
        if: env.BRANCH_NAME == 'dev'
        uses: mamal72/minio-perfect-deploy-action@main
        continue-on-error: true
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'fire-recovery-web'
          source_dir: 'src'
          target_dir: '/dev'